from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^login$',views.generatetest,name='generatetest'),
	url(r'^test$',views.index,name='index'),
	url(r'^test/',views.erro,name='error'),
	url(r'^login/',views.erro,name='error'),
	url(r'^starttest$',views.starttest,name='starttest'),
	url(r'^testc$',views.testc,name="testc"),
	url(r'^teacherlogin$',views.teacherlogin,name="teacher_login"),
	url(r'^logout$',views.logout,name="logout"),
	url(r'^profile$',views.profile,name="profile"),
	url(r'^updateiddetail$',views.updateiddetail,name="updateid"),
	url(r'^updatepassdetail',views.updatepassdetail,name="updatepass"),
	url(r'^creteststart$',views.creteststart,name="create_test_start"),
	url(r'^cretest$',views.cretest,name="create_test"),
	url(r'^cretestf$',views.cretestf,name="start_paper"),
	url(r'^submitt$',views.submit,name="submit_test"),
	url(r'^underconstruction$',views.underconstruction,name="underconstruction_site"),
	url(r'^edittest$',views.edittest,name="edit_test"),
	url(r'^edittestoption$',views.edittestoption,name="edit"),
	url(r'^prevedittest$',views.prevedittest,name="start_from_previous"),
	url(r'^perticularedittest$',views.perticularedittest,name="perticular_test_edit"),
	url(r'^equestion$',views.equestion,name="edit_question_with_number"),
	url(r'^updatesave$',views.updatesave,name="update_and_save"),
	url(r'^publishtest$',views.publishtest,name="publish test"),
	url(r'^publishselected$',views.publishselected,name="punlish_selected_paper"),
	url(r'^publishunselected$',views.publishunselected,name="unpublish_selected_paper"),
	url(r'^reviewpaper1$',views.reviewpaper1,name="review_the_paper"),
	url(r'^reviewpaper2$',views.reviewpaper2,name="review_the_selected_paper"),
	url(r'^result$',views.result,name="result_of_paper"),
	url(r'^result_gen_option$',views.result_gen_option,name="result_gen_options"),
	url(r'^checkstudentresult$',views.checkstudentresult,name="check_for_particular_result"),
	url(r'^show_ques_wise_result$',views.show_ques_wise_result,name="show_question_wise_result_of_students"),
	url(r'^downloadcsv$',views.downloadcsv,name="download_csv_file"),
]
